name: Create a PDF and push it to repo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag main_image
    - name: Run container
      run: docker run --name main_container main_image
    - name: Get PDF from container
      run: docker cp main_container:./main.pdf .
    - name: Push PDF
      run: |
        git config --global user.name 'Grigory Burmashev'
        git config --global user.email 'Burmashev@users.noreply.github.com'
        git fetch 
        git add .
        git checkout pdf
        git commit -m "Push PDF"
        git push
